//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEf2
{
    using System;
    using System.Collections.Generic;
    
    public partial class nj_news
    {
        public string NEWS_ID { get; set; }
        public string CID { get; set; }
        public string TITLE { get; set; }
        public string CONTENTS { get; set; }
        public string SOURCE { get; set; }
        public string COUNTS { get; set; }
        public string CREATETIME { get; set; }
        public string FOOTER { get; set; }
    }
}
