//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int id { get; set; }
        public string Username { get; set; }
        public string Passwd { get; set; }
        public string oskey { get; set; }
        public string type { get; set; }
        public Nullable<int> site { get; set; }
        public string managekind { get; set; }
        public string content { get; set; }
        public string shichang { get; set; }
    }
}
